default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: simpleadmin_development

test:
  <<: *default
  database: simpleadmin_test

production:
  <<: *default
  database: simpleadmin_production
  username: simpleadmin
  password: <%= ENV['SIMPLEADMIN_DATABASE_PASSWORD'] %>
